@startuml
title Diagrama de Sequencia para delete

actor Usuário
Boundary Frontend
Boundary SpringBoot
Control taskController
Participant taskService
Participant taskRepository
Database TodoList

Usuário -> Frontend: Deleta tarefa
activate Usuário
activate Frontend
Frontend -> SpringBoot: DELETE /todo-list/task/{id}
activate SpringBoot
SpringBoot -> taskController: delete(id)
activate taskController
taskController -> taskService: delete(id)
activate taskService
taskService -> taskRepository: findById(id)
activate taskRepository
taskRepository -> TodoList: SELECT * FROM Tasks WHERE id = {id}
TodoList --> taskRepository: Task
taskRepository --> taskService: Task
deactivate taskRepository
taskService -> taskRepository: deleteById(id)
activate taskRepository
taskRepository -> TodoList: DELETE FROM Tasks WHERE id = {id}
TodoList --> taskRepository: void
taskRepository --> taskService: void
deactivate taskRepository
taskService --> taskController: void
deactivate taskService
taskController --> SpringBoot: ResponseEntity.noContent()
deactivate taskController
SpringBoot --> Frontend: ResponseEntity.noContent()
deactivate SpringBoot
Frontend --> Usuário: Confirmação de exclusão
deactivate Frontend
deactivate Usuário
@enduml
